# Generated by Django 5.2 on 2025-04-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_credits_created_at_credits_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
