# Generated by Django 5.2 on 2025-04-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_phone', models.CharField(help_text='Recipient phone number', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sender_id', models.CharField(blank=True, help_text='Sender ID used (e.g., company name)', max_length=70)),
                ('message_body', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'SMS Log',
                'ordering': ['-sent_at'],
            },
        ),
    ]
