# Generated by Django 5.2 on 2025-04-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, default='piece', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='shops.shops')),
            ],
            options={
                'verbose_name_plural': 'Stock Items Definitions',
                'ordering': ['shop', 'item_type', 'item_name'],
                'unique_together': {('shop', 'item_name', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(help_text='Positive for additions, negative for removals/usage.')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('director_name', models.CharField(max_length=30)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='shops.shops')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs', to='stock.stockitem')),
            ],
            options={
                'verbose_name_plural': 'Stock Change Log',
                'ordering': ['-log_date'],
            },
        ),
    ]
