# Generated by Django 5.2 on 2025-04-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_packages_water_amount_label'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['shop', 'item_name', 'item_type'], 'verbose_name_plural': 'Stock Items Definitions'},
        ),
        migrations.AddField(
            model_name='stockitem',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Associated package (for bottles only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='packages.packages'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='item_name',
            field=models.CharField(choices=[('Bottle', 'Bottle'), ('Cap', 'Cap'), ('Label', 'Label'), ('Shrink Wrap', 'Shrink Wrap')], help_text='Category of inventory item', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='item_type',
            field=models.CharField(help_text='Specific type within the category', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(default='piece', max_length=20),
        ),
    ]
