# Generated by Django 5.2 on 2025-04-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stockitem_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='item_name',
            field=models.CharField(choices=[('Bottle', 'Bottle'), ('Cap', 'Cap'), ('Label', 'Label'), ('Shrink Wrap', 'Shrink Wrap'), ('Water Bundle', 'Water Bundle')], help_text='Category of inventory item', max_length=100),
        ),
    ]
