# Generated by Django 5.2 on 2025-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stockitem_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='reorder_point',
            field=models.IntegerField(default=300, help_text='Stock level at which reordering is recommended'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='threshold',
            field=models.IntegerField(default=200, help_text='Threshold level for low stock warning'),
        ),
    ]
