# Generated by Django 5.2 on 2025-04-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stockitem_reorder_point_stockitem_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklog',
            name='log_date',
            field=models.DateTimeField(),
        ),
    ]
