# Generated by Django 5.2 on 2025-04-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refills',
            name='free_quantity',
            field=models.IntegerField(default=0, help_text='Number of free refills in this transaction.'),
        ),
        migrations.AddField(
            model_name='refills',
            name='is_partially_free',
            field=models.BooleanField(default=False, help_text='True if this refill contains both free and paid portions.'),
        ),
        migrations.AddField(
            model_name='refills',
            name='loyalty_refill_count',
            field=models.IntegerField(default=0, help_text='Number of refills to count toward loyalty program.'),
        ),
        migrations.AddField(
            model_name='refills',
            name='paid_quantity',
            field=models.IntegerField(default=0, help_text='Number of paid refills in this transaction.'),
        ),
    ]
