# Generated by Django 5.2 on 2025-04-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0002_refills_free_quantity_refills_is_partially_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refills',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
