# Generated by Django 5.2 on 2025-04-04 13:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('REFILL', 'Refill'), ('SALE', 'Sale')], default='REFILL', max_length=10)),
                ('bottle_type', models.CharField(blank=True, default='', help_text="e.g., 'Standard 20L Bottle', 'Dispenser Bottle'", max_length=40)),
                ('water_amount_label', models.CharField(help_text="Label for water amount, e.g., '10L'", max_length=15)),
                ('description', models.CharField(blank=True, help_text='Optional extra description if needed', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='shops.shops')),
            ],
            options={
                'verbose_name_plural': 'Packages',
                'ordering': ['shop', 'sale_type', 'price'],
                'unique_together': {('shop', 'sale_type', 'water_amount_label', 'bottle_type', 'description', 'price')},
            },
        ),
    ]
