# Generated by Django 5.2 on 2025-04-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='bottle_type',
            field=models.CharField(blank=True, choices=[('DISPOSABLE', 'Disposable'), ('HARD', 'Hard'), ('REFILL', 'Refill'), ('LOYAL_CUSTOMER', 'Loyal Customer'), ('DIRECTOR', 'Director'), ('BUNDLE', 'Bundle')], help_text='Bottle type (only required for Sale type: Disposable, Hard, Refill, Loyal Customer, Director, or Bundle)', max_length=40, null=True),
        ),
    ]
