# Generated by Django 5.2 on 2025-04-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_packages_bottle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='water_amount_label',
            field=models.IntegerField(help_text='Amount of water in Liters (e.g., 5, 10, 20)'),
        ),
    ]
