# Generated by Django 5.2 on 2025-04-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_packages_water_amount_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='water_amount_label',
            field=models.DecimalField(decimal_places=1, help_text='Amount of water in Liters (e.g., 5.00, 10.5, 20.75)', max_digits=5),
        ),
    ]
