# Generated by Django 5.2 on 2025-04-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_packages_water_amount_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='bottle_type',
            field=models.CharField(blank=True, choices=[('DISPOSABLE', 'Disposable'), ('HARD', 'Hard'), ('REFILL', 'Refill'), ('LOYAL_CUSTOMER', 'Loyal Customer'), ('LOYAL_CUSTOMER_MBURU', 'Loyal Customer Mburu'), ('DIRECTOR', 'Director'), ('BUNDLE', 'Bundle')], help_text='Bottle type (only required for Sale type: Disposable, Hard, Refill, Loyal Customer, Director, or Bundle)', max_length=40, null=True),
        ),
    ]
