# Generated by Django 5.2 on 2025-04-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=30)),
                ('value', models.FloatField(help_text='The reading value from the meter.')),
                ('meter_photo', models.ImageField(blank=True, null=True, upload_to='meter_reading_photos/')),
                ('reading_type', models.CharField(choices=[('Blue Machine Right', 'Blue Machine Right'), ('Blue Machine Left', 'Blue Machine Left'), ('Blue Machine', 'Blue Machine'), ('Purifier Machine', 'Purifier Machine')], max_length=30)),
                ('reading_date', models.DateField(auto_now_add=True)),
                ('reading_time', models.TimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='shops.shops')),
            ],
            options={
                'verbose_name_plural': 'Meter Readings',
                'ordering': ['-reading_date', '-reading_time'],
                'unique_together': {('shop', 'reading_date', 'reading_type')},
            },
        ),
    ]
