# Generated by Django 5.2 on 2025-04-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='reading_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='reading_time',
            field=models.TimeField(),
        ),
    ]
