# Generated by Django 5.2 on 2025-04-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=14, unique=True)),
                ('apartment_name', models.CharField(blank=True, max_length=50)),
                ('room_number', models.CharField(blank=True, max_length=30)),
                ('date_registered', models.DateTimeField(auto_now_add=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='shops.shops')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
