# Generated by Django 5.2 on 2025-04-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
