# Generated by Django 5.2 on 2025-04-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date_registered',
            field=models.DateTimeField(null=True),
        ),
    ]
