# Generated by Django 5.2 on 2025-04-04 13:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('packages', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('payment_mode', models.CharField(choices=[('MPESA', 'MPESA'), ('CASH', 'CASH'), ('CREDIT', 'Credit')], default='CASH', max_length=7)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivered', models.IntegerField(blank=True, help_text='Null=Not Delivered, 0=Delivered(Free), >0 = Delivery Fee Charged', null=True)),
                ('sold_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('agent_name', models.CharField(default='Unknown', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customers.customers')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='packages.packages')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='shops.shops')),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'ordering': ['-sold_at'],
            },
        ),
    ]
