# Generated by Django 5.2 on 2025-04-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sold_at',
            field=models.DateTimeField(null=True),
        ),
    ]
